name: Publish to PyPI
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    if: "contains(github.event.head_commit.message, 'version bump')"
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install hatch
    - name: Build package
      run: hatch build
    - name: Test package
      run: hatch run dev:run-tests
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
